import { Language } from "@/types/language";

export const languages: Language[] = [
  { id: 102, value: "javascript", label: "JavaScript (Node.js 22.08.0)" },
  { id: 45, value: "nasm", label: "Assembly (NASM 2.14.02)" },
  { id: 46, value: "shell", label: "Bash (5.0.0)" },
  { id: 47, value: "vb", label: "Basic (FBC 1.07.1)" },
  { id: 104, value: "c", label: "C (Clang 18.1.8)" },
  { id: 75, value: "c", label: "C (Clang 7.0.1)" },
  { id: 76, value: "cpp", label: "C++ (Clang 7.0.1)" },
  { id: 103, value: "c", label: "C (GCC 14.1.0)" },
  { id: 105, value: "cpp", label: "C++ (GCC 14.1.0)" },
  { id: 48, value: "c", label: "C (GCC 7.4.0)" },
  { id: 52, value: "cpp", label: "C++ (GCC 7.4.0)" },
  { id: 49, value: "c", label: "C (GCC 8.3.0)" },
  { id: 53, value: "cpp", label: "C++ (GCC 8.3.0)" },
  { id: 50, value: "c", label: "C (GCC 9.2.0)" },
  { id: 54, value: "cpp", label: "C++ (GCC 9.2.0)" },
  { id: 86, value: "clojure", label: "Clojure (1.10.1)" },
  { id: 51, value: "csharp", label: "C# (Mono 6.6.0.161)" },
  { id: 77, value: "cobol", label: "COBOL (GnuCOBOL 2.2)" },
  { id: 55, value: "lisp", label: "Common Lisp (SBCL 2.0.0)" },
  { id: 90, value: "dart", label: "Dart (2.19.2)" },
  { id: 56, value: "d", label: "D (DMD 2.089.1)" },
  { id: 57, value: "elixir", label: "Elixir (1.9.4)" },
  { id: 58, value: "erlang", label: "Erlang (OTP 22.2)" },
  { id: 44, value: "plaintext", label: "Executable" },
  { id: 87, value: "fsharp", label: "F# (.NET Core SDK 3.1.202)" },
  { id: 59, value: "fortran", label: "Fortran (GFortran 9.2.0)" },
  { id: 60, value: "go", label: "Go (1.13.5)" },
  { id: 95, value: "go", label: "Go (1.18.5)" },
  { id: 88, value: "groovy", label: "Groovy (3.0.3)" },
  { id: 61, value: "haskell", label: "Haskell (GHC 8.8.1)" },
  { id: 96, value: "java", label: "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)" },
  { id: 91, value: "java", label: "Java (JDK 17.0.6)" },
  { id: 62, value: "java", label: "Java (OpenJDK 13.0.1)" },
  { id: 93, value: "javascript", label: "JavaScript (Node.js 18.15.0)" },
  { id: 97, value: "javascript", label: "JavaScript (Node.js 20.17.0)" },
  { id: 78, value: "kotlin", label: "Kotlin (1.3.70)" },
  { id: 64, value: "lua", label: "Lua (5.3.5)" },
  { id: 89, value: "plaintext", label: "Multi-file program" },
  { id: 79, value: "objective-c", label: "Objective-C (Clang 7.0.1)" },
  { id: 65, value: "ocaml", label: "OCaml (4.09.0)" },
  { id: 66, value: "matlab", label: "Octave (5.1.0)" },
  { id: 67, value: "pascal", label: "Pascal (FPC 3.0.4)" },
  { id: 85, value: "perl", label: "Perl (5.28.1)" },
  { id: 68, value: "php", label: "PHP (7.4.1)" },
  { id: 98, value: "php", label: "PHP (8.3.11)" },
  { id: 43, value: "plaintext", label: "Plain Text" },
  { id: 69, value: "prolog", label: "Prolog (GNU Prolog 1.4.5)" },
  { id: 70, value: "python", label: "Python (2.7.17)" },
  { id: 92, value: "python", label: "Python (3.11.2)" },
  { id: 100, value: "python", label: "Python (3.12.5)" },
  { id: 71, value: "python", label: "Python (3.8.1)" },
  { id: 80, value: "r", label: "R (4.0.0)" },
  { id: 99, value: "r", label: "R (4.4.1)" },
  { id: 72, value: "ruby", label: "Ruby (2.7.0)" },
  { id: 73, value: "rust", label: "Rust (1.40.0)" },
  { id: 81, value: "scala", label: "Scala (2.13.2)" },
  { id: 82, value: "sql", label: "SQL (SQLite 3.27.2)" },
  { id: 83, value: "swift", label: "Swift (5.2.3)" },
  { id: 74, value: "typescript", label: "TypeScript (3.7.4)" },
  { id: 94, value: "typescript", label: "TypeScript (5.0.3)" },
  { id: 101, value: "typescript", label: "TypeScript (5.6.2)" },
  { id: 84, value: "vb", label: "Visual Basic.Net (vbnc 0.0.0.5943)" },
];
