import { Language } from "@/types/language";

export const languages: Language[] = [
  {
    id: 102,
    value: "javascript",
    label: "JavaScript (Node.js 22.08.0)",
    sampleFileName: "app.js",
    icon: "/devicons/javascript/javascript-original.svg",
  },
  {
    id: 45,
    value: "nasm",
    label: "Assembly (NASM 2.14.02)",
    sampleFileName: "hello.asm",
    icon: "/devicons/wasm/wasm-original.svg",
  },
  {
    id: 46,
    value: "shell",
    label: "Bash (5.0.0)",
    sampleFileName: "run.sh",
    icon: "/devicons/bash/bash-original.svg",
  },
  {
    id: 47,
    value: "vb",
    label: "Basic (FBC 1.07.1)",
    sampleFileName: "hello.bas",
    icon: "/devicons/visualbasic/visualbasic-original.svg",
  },
  {
    id: 104,
    value: "c",
    label: "C (Clang 18.1.8)",
    sampleFileName: "main.c",
    icon: "/devicons/c/c-original.svg",
  },
  {
    id: 75,
    value: "c",
    label: "C (Clang 7.0.1)",
    sampleFileName: "solution.c",
    icon: "/devicons/c/c-original.svg",
  },
  {
    id: 76,
    value: "cpp",
    label: "C++ (Clang 7.0.1)",
    sampleFileName: "solution.cpp",
    icon: "/devicons/cplusplus/cplusplus-original.svg",
  },
  {
    id: 103,
    value: "c",
    label: "C (GCC 14.1.0)",
    sampleFileName: "program.c",
    icon: "/devicons/c/c-original.svg",
  },
  {
    id: 105,
    value: "cpp",
    label: "C++ (GCC 14.1.0)",
    sampleFileName: "program.cpp",
    icon: "/devicons/cplusplus/cplusplus-original.svg",
  },
  {
    id: 48,
    value: "c",
    label: "C (GCC 7.4.0)",
    sampleFileName: "program.c",
    icon: "/devicons/c/c-original.svg",
  },
  {
    id: 52,
    value: "cpp",
    label: "C++ (GCC 7.4.0)",
    sampleFileName: "program.cpp",
    icon: "/devicons/cplusplus/cplusplus-original.svg",
  },
  {
    id: 49,
    value: "c",
    label: "C (GCC 8.3.0)",
    sampleFileName: "program.c",
    icon: "/devicons/c/c-original.svg",
  },
  {
    id: 53,
    value: "cpp",
    label: "C++ (GCC 8.3.0)",
    sampleFileName: "program.cpp",
    icon: "/devicons/cplusplus/cplusplus-original.svg",
  },
  {
    id: 50,
    value: "c",
    label: "C (GCC 9.2.0)",
    sampleFileName: "program.c",
    icon: "/devicons/c/c-original.svg",
  },
  {
    id: 54,
    value: "cpp",
    label: "C++ (GCC 9.2.0)",
    sampleFileName: "program.cpp",
    icon: "/devicons/cplusplus/cplusplus-original.svg",
  },
  {
    id: 86,
    value: "clojure",
    label: "Clojure (1.10.1)",
    sampleFileName: "core.clj",
    icon: "/devicons/clojure/clojure-original.svg",
  },
  {
    id: 51,
    value: "csharp",
    label: "C# (Mono 6.6.0.161)",
    sampleFileName: "Solution.cs",
    icon: "/devicons/csharp/csharp-original.svg",
  },
  {
    id: 77,
    value: "cobol",
    label: "COBOL (GnuCOBOL 2.2)",
    sampleFileName: "HELLO.cob",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 55,
    value: "lisp",
    label: "Common Lisp (SBCL 2.0.0)",
    sampleFileName: "script.lisp",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 90,
    value: "dart",
    label: "Dart (2.19.2)",
    sampleFileName: "main.dart",
    icon: "/devicons/dart/dart-original.svg",
  },
  {
    id: 56,
    value: "d",
    label: "D (DMD 2.089.1)",
    sampleFileName: "app.d",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 57,
    value: "elixir",
    label: "Elixir (1.9.4)",
    sampleFileName: "solution.exs",
    icon: "/devicons/elixir/elixir-original.svg",
  },
  {
    id: 58,
    value: "erlang",
    label: "Erlang (OTP 22.2)",
    sampleFileName: "solution.erl",
    icon: "/devicons/erlang/erlang-original.svg",
  },
  {
    id: 44,
    value: "plaintext",
    label: "Executable",
    sampleFileName: "a.out",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 87,
    value: "fsharp",
    label: "F# (.NET Core SDK 3.1.202)",
    sampleFileName: "Program.fs",
    icon: "/devicons/fsharp/fsharp-original.svg",
  },
  {
    id: 59,
    value: "fortran",
    label: "Fortran (GFortran 9.2.0)",
    sampleFileName: "main.f90",
    icon: "/devicons/fortran/fortran-original.svg",
  },
  {
    id: 60,
    value: "go",
    label: "Go (1.13.5)",
    sampleFileName: "main.go",
    icon: "/devicons/go/go-original.svg",
  },
  {
    id: 88,
    value: "groovy",
    label: "Groovy (3.0.3)",
    sampleFileName: "Script.groovy",
    icon: "/devicons/groovy/groovy-original.svg",
  },
  {
    id: 61,
    value: "haskell",
    label: "Haskell (GHC 8.8.1)",
    sampleFileName: "Solution.hs",
    icon: "/devicons/haskell/haskell-original.svg",
  },
  {
    id: 96,
    value: "java",
    label: "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)",
    sampleFileName: "App.java",
    icon: "/devicons/java/java-original.svg",
  },
  {
    id: 91,
    value: "java",
    label: "Java (JDK 17.0.6)",
    sampleFileName: "Solution.java",
    icon: "/devicons/java/java-original.svg",
  },
  {
    id: 62,
    value: "java",
    label: "Java (OpenJDK 13.0.1)",
    sampleFileName: "Main.java",
    icon: "/devicons/java/java-original.svg",
  },
  {
    id: 93,
    value: "javascript",
    label: "JavaScript (Node.js 18.15.0)",
    sampleFileName: "index.js",
    icon: "/devicons/javascript/javascript-original.svg",
  },
  {
    id: 97,
    value: "javascript",
    label: "JavaScript (Node.js 20.17.0)",
    sampleFileName: "solution.js",
    icon: "/devicons/javascript/javascript-original.svg",
  },
  {
    id: 78,
    value: "kotlin",
    label: "Kotlin (1.3.70)",
    sampleFileName: "Solution.kt",
    icon: "/devicons/kotlin/kotlin-original.svg",
  },
  {
    id: 64,
    value: "lua",
    label: "Lua (5.3.5)",
    sampleFileName: "solution.lua",
    icon: "/devicons/lua/lua-original.svg",
  },
  {
    id: 89,
    value: "plaintext",
    label: "Multi-file program",
    sampleFileName: "README.md",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 79,
    value: "objective-c",
    label: "Objective-C (Clang 7.0.1)",
    sampleFileName: "main.m",
    icon: "/devicons/objectivec/objectivec-plain.svg",
  },
  {
    id: 65,
    value: "ocaml",
    label: "OCaml (4.09.0)",
    sampleFileName: "solution.ml",
    icon: "/devicons/ocaml/ocaml-original.svg",
  },
  {
    id: 66,
    value: "matlab",
    label: "Octave (5.1.0)",
    sampleFileName: "script.m",
    icon: "/devicons/matlab/matlab-original.svg",
  },
  {
    id: 67,
    value: "pascal",
    label: "Pascal (FPC 3.0.4)",
    sampleFileName: "solution.pas",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 85,
    value: "perl",
    label: "Perl (5.28.1)",
    sampleFileName: "solution.pl",
    icon: "/devicons/perl/perl-original.svg",
  },
  {
    id: 68,
    value: "php",
    label: "PHP (7.4.1)",
    sampleFileName: "index.php",
    icon: "/devicons/php/php-original.svg",
  },
  {
    id: 98,
    value: "php",
    label: "PHP (8.3.11)",
    sampleFileName: "solution.php",
    icon: "/devicons/php/php-original.svg",
  },
  {
    id: 43,
    value: "plaintext",
    label: "Plain Text",
    sampleFileName: "notes.txt",
    icon: "/devicons/code/code-original.svg",
  },
  {
    id: 69,
    value: "prolog",
    label: "Prolog (GNU Prolog 1.4.5)",
    sampleFileName: "solution.pl",
    icon: "/devicons/prolog/prolog-original.svg",
  },
  {
    id: 70,
    value: "python",
    label: "Python (2.7.17)",
    sampleFileName: "solution.py",
    icon: "/devicons/python/python-original.svg",
  },
  {
    id: 92,
    value: "python",
    label: "Python (3.11.2)",
    sampleFileName: "main.py",
    icon: "/devicons/python/python-original.svg",
  },
  {
    id: 100,
    value: "python",
    label: "Python (3.12.5)",
    sampleFileName: "app.py",
    icon: "/devicons/python/python-original.svg",
  },
  {
    id: 71,
    value: "python",
    label: "Python (3.8.1)",
    sampleFileName: "script.py",
    icon: "/devicons/python/python-original.svg",
  },
  {
    id: 80,
    value: "r",
    label: "R (4.0.0)",
    sampleFileName: "script.R",
    icon: "/devicons/r/r-original.svg",
  },
  {
    id: 99,
    value: "r",
    label: "R (4.4.1)",
    sampleFileName: "analysis.R",
    icon: "/devicons/r/r-original.svg",
  },
  {
    id: 72,
    value: "ruby",
    label: "Ruby (2.7.0)",
    sampleFileName: "solution.rb",
    icon: "/devicons/ruby/ruby-original.svg",
  },
  {
    id: 73,
    value: "rust",
    label: "Rust (1.40.0)",
    sampleFileName: "main.rs",
    icon: "/devicons/rust/rust-original.svg",
  },
  {
    id: 81,
    value: "scala",
    label: "Scala (2.13.2)",
    sampleFileName: "Solution.scala",
    icon: "/devicons/scala/scala-original.svg",
  },
  {
    id: 82,
    value: "sql",
    label: "SQL (SQLite 3.27.2)",
    sampleFileName: "query.sql",
    icon: "/devicons/sqlite/sqlite-original.svg",
  },
  {
    id: 83,
    value: "swift",
    label: "Swift (5.2.3)",
    sampleFileName: "main.swift",
    icon: "/devicons/swift/swift-original.svg",
  },
  {
    id: 74,
    value: "typescript",
    label: "TypeScript (3.7.4)",
    sampleFileName: "index.ts",
    icon: "/devicons/typescript/typescript-original.svg",
  },
  {
    id: 94,
    value: "typescript",
    label: "TypeScript (5.0.3)",
    sampleFileName: "app.ts",
    icon: "/devicons/typescript/typescript-original.svg",
  },
  {
    id: 101,
    value: "typescript",
    label: "TypeScript (5.6.2)",
    sampleFileName: "solution.ts",
    icon: "/devicons/typescript/typescript-original.svg",
  },
  {
    id: 84,
    value: "vb",
    label: "Visual Basic.Net (vbnc 0.0.0.5943)",
    sampleFileName: "Program.vb",
    icon: "/devicons/visualbasic/visualbasic-original.svg",
  },
];
