import { Language } from "@/types/language";

export const languages: Language[] = [
  {
    id: 102,
    value: "javascript",
    label: "JavaScript (Node.js 22.08.0)",
    sampleFileName: "app.js",
  },
  {
    id: 45,
    value: "nasm",
    label: "Assembly (NASM 2.14.02)",
    sampleFileName: "hello.asm",
  },
  { id: 46, value: "shell", label: "Bash (5.0.0)", sampleFileName: "run.sh" },
  {
    id: 47,
    value: "vb",
    label: "Basic (FBC 1.07.1)",
    sampleFileName: "hello.bas",
  },
  { id: 104, value: "c", label: "C (Clang 18.1.8)", sampleFileName: "main.c" },
  {
    id: 75,
    value: "c",
    label: "C (Clang 7.0.1)",
    sampleFileName: "solution.c",
  },
  {
    id: 76,
    value: "cpp",
    label: "C++ (Clang 7.0.1)",
    sampleFileName: "solution.cpp",
  },
  { id: 103, value: "c", label: "C (GCC 14.1.0)", sampleFileName: "program.c" },
  {
    id: 105,
    value: "cpp",
    label: "C++ (GCC 14.1.0)",
    sampleFileName: "program.cpp",
  },
  { id: 48, value: "c", label: "C (GCC 7.4.0)", sampleFileName: "program.c" },
  {
    id: 52,
    value: "cpp",
    label: "C++ (GCC 7.4.0)",
    sampleFileName: "program.cpp",
  },
  { id: 49, value: "c", label: "C (GCC 8.3.0)", sampleFileName: "program.c" },
  {
    id: 53,
    value: "cpp",
    label: "C++ (GCC 8.3.0)",
    sampleFileName: "program.cpp",
  },
  { id: 50, value: "c", label: "C (GCC 9.2.0)", sampleFileName: "program.c" },
  {
    id: 54,
    value: "cpp",
    label: "C++ (GCC 9.2.0)",
    sampleFileName: "program.cpp",
  },
  {
    id: 86,
    value: "clojure",
    label: "Clojure (1.10.1)",
    sampleFileName: "core.clj",
  },
  {
    id: 51,
    value: "csharp",
    label: "C# (Mono 6.6.0.161)",
    sampleFileName: "Solution.cs",
  },
  {
    id: 77,
    value: "cobol",
    label: "COBOL (GnuCOBOL 2.2)",
    sampleFileName: "HELLO.cob",
  },
  {
    id: 55,
    value: "lisp",
    label: "Common Lisp (SBCL 2.0.0)",
    sampleFileName: "script.lisp",
  },
  {
    id: 90,
    value: "dart",
    label: "Dart (2.19.2)",
    sampleFileName: "main.dart",
  },
  { id: 56, value: "d", label: "D (DMD 2.089.1)", sampleFileName: "app.d" },
  {
    id: 57,
    value: "elixir",
    label: "Elixir (1.9.4)",
    sampleFileName: "solution.exs",
  },
  {
    id: 58,
    value: "erlang",
    label: "Erlang (OTP 22.2)",
    sampleFileName: "solution.erl",
  },
  { id: 44, value: "plaintext", label: "Executable", sampleFileName: "a.out" },
  {
    id: 87,
    value: "fsharp",
    label: "F# (.NET Core SDK 3.1.202)",
    sampleFileName: "Program.fs",
  },
  {
    id: 59,
    value: "fortran",
    label: "Fortran (GFortran 9.2.0)",
    sampleFileName: "main.f90",
  },
  { id: 60, value: "go", label: "Go (1.13.5)", sampleFileName: "main.go" },
  { id: 95, value: "go", label: "Go (1.18.5)", sampleFileName: "solution.go" },
  {
    id: 88,
    value: "groovy",
    label: "Groovy (3.0.3)",
    sampleFileName: "Script.groovy",
  },
  {
    id: 61,
    value: "haskell",
    label: "Haskell (GHC 8.8.1)",
    sampleFileName: "Solution.hs",
  },
  {
    id: 96,
    value: "java",
    label: "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)",
    sampleFileName: "App.java",
  },
  {
    id: 91,
    value: "java",
    label: "Java (JDK 17.0.6)",
    sampleFileName: "Solution.java",
  },
  {
    id: 62,
    value: "java",
    label: "Java (OpenJDK 13.0.1)",
    sampleFileName: "Main.java",
  },
  {
    id: 93,
    value: "javascript",
    label: "JavaScript (Node.js 18.15.0)",
    sampleFileName: "index.js",
  },
  {
    id: 97,
    value: "javascript",
    label: "JavaScript (Node.js 20.17.0)",
    sampleFileName: "solution.js",
  },
  {
    id: 78,
    value: "kotlin",
    label: "Kotlin (1.3.70)",
    sampleFileName: "Solution.kt",
  },
  {
    id: 64,
    value: "lua",
    label: "Lua (5.3.5)",
    sampleFileName: "solution.lua",
  },
  {
    id: 89,
    value: "plaintext",
    label: "Multi-file program",
    sampleFileName: "README.md",
  },
  {
    id: 79,
    value: "objective-c",
    label: "Objective-C (Clang 7.0.1)",
    sampleFileName: "main.m",
  },
  {
    id: 65,
    value: "ocaml",
    label: "OCaml (4.09.0)",
    sampleFileName: "solution.ml",
  },
  {
    id: 66,
    value: "matlab",
    label: "Octave (5.1.0)",
    sampleFileName: "script.m",
  },
  {
    id: 67,
    value: "pascal",
    label: "Pascal (FPC 3.0.4)",
    sampleFileName: "solution.pas",
  },
  {
    id: 85,
    value: "perl",
    label: "Perl (5.28.1)",
    sampleFileName: "solution.pl",
  },
  { id: 68, value: "php", label: "PHP (7.4.1)", sampleFileName: "index.php" },
  {
    id: 98,
    value: "php",
    label: "PHP (8.3.11)",
    sampleFileName: "solution.php",
  },
  {
    id: 43,
    value: "plaintext",
    label: "Plain Text",
    sampleFileName: "notes.txt",
  },
  {
    id: 69,
    value: "prolog",
    label: "Prolog (GNU Prolog 1.4.5)",
    sampleFileName: "solution.pl",
  },
  {
    id: 70,
    value: "python",
    label: "Python (2.7.17)",
    sampleFileName: "solution.py",
  },
  {
    id: 92,
    value: "python",
    label: "Python (3.11.2)",
    sampleFileName: "main.py",
  },
  {
    id: 100,
    value: "python",
    label: "Python (3.12.5)",
    sampleFileName: "app.py",
  },
  {
    id: 71,
    value: "python",
    label: "Python (3.8.1)",
    sampleFileName: "script.py",
  },
  { id: 80, value: "r", label: "R (4.0.0)", sampleFileName: "script.R" },
  { id: 99, value: "r", label: "R (4.4.1)", sampleFileName: "analysis.R" },
  {
    id: 72,
    value: "ruby",
    label: "Ruby (2.7.0)",
    sampleFileName: "solution.rb",
  },
  { id: 73, value: "rust", label: "Rust (1.40.0)", sampleFileName: "main.rs" },
  {
    id: 81,
    value: "scala",
    label: "Scala (2.13.2)",
    sampleFileName: "Solution.scala",
  },
  {
    id: 82,
    value: "sql",
    label: "SQL (SQLite 3.27.2)",
    sampleFileName: "query.sql",
  },
  {
    id: 83,
    value: "swift",
    label: "Swift (5.2.3)",
    sampleFileName: "main.swift",
  },
  {
    id: 74,
    value: "typescript",
    label: "TypeScript (3.7.4)",
    sampleFileName: "index.ts",
  },
  {
    id: 94,
    value: "typescript",
    label: "TypeScript (5.0.3)",
    sampleFileName: "app.ts",
  },
  {
    id: 101,
    value: "typescript",
    label: "TypeScript (5.6.2)",
    sampleFileName: "solution.ts",
  },
  {
    id: 84,
    value: "vb",
    label: "Visual Basic.Net (vbnc 0.0.0.5943)",
    sampleFileName: "Program.vb",
  },
];
